### ISSUE TITLE
You solved an stackoverflow issue by writing this plugin!

### ISSUE THREAD

**Issue by biotician** [itchyny/lightline.vim#105]
I decided to write my own statusline from scratch and by looking for solutions in your code, and I found a great solution to a [problem on stackoverflow](http://stackoverflow.com/questions/15561132/run-command-when-vim-enters-visual-mode/30678919#30678919): Triggering Visual mode (there isn't any autocmd dedicated to this event). I quoted your source code in the thread.
Thank you for the solutions you brought!

**Comment by itchyny** [comment]
This method is used by powerline, the ancestor plugin of lightline and I just imitated. So that's not what I found. Also, since the function is called every time on cursor moving, so it's better to cache the mode and finish the function instantly if the mode is not changed, so that the function does not affect the performance. Anyway, it looks like the best solution to the question in that stackoverflow thread.

**Comment by biotician** [comment]
All right, I edited the thread.
Performance also matters.
