### ISSUE TITLE
Evaluate component_expand per window

### ISSUE THREAD

**Issue by noscript** [itchyny/lightline.vim#161]
I'm trying to access a window number inside `component_expand` function but I always get the number of the current window.

How to reproduce:

```vim
let g:lightline.active = {'left': ['test']}
let g:lightline.inactive = {'left': ['test']}
let g:lightline.component_expand = { 'test' : 'MyTest' }
let g:lightline.component_type = { 'test' : 'error' }
fu! MyTest()
	return winnr()
endfu
```

**Comment by itchyny** [comment]
How about this?
```vim
fu! MyTest()
    return '%{winnr()}'
endfu
```

**Comment by noscript** [comment]
Thank you!

**Comment by joshuarubin** [comment]
This is still an issue if `MyTest()` were to need to return statusline fields like `'%m'`. Those fields are put in the status line literally and are not evaluated. As a result, this kind of logic is deceivingly wrong:

```vim
fu! MyTest()
  if winwidth(0) < 70
    return ""
  endif

  if &filetype =~ 'vimfiler'
    return ""
  endif

  return '%3p%%  %l/%L☰ :%3v'
endfu
```

because it `winwidth` and `filetype` are evaluated in the current window, not necessarily the window of the statusline (which differs for inactive components).

**Comment by noscript** [comment]
I'm afraid you have to evaluate stuff like `%m` manually:
```vim
let g:lightline.component_expand = {
	\ 'mytest' : 'MyTestPre'
\}

fu! MyTestPre()
	return '%{MyTest()}'
endfu

fu! MyTest()
	if winwidth(0) < 70
		return "[less 70]"
	else
		" evaluate %l / %L
		return string(line(".")) . ' / ' . string(line("$"))
	endif
endfu
```

I would love to know if there is a better way.
