### ISSUE TITLE
component_visible_condition should contain by default "spell"

### ISSUE THREAD

**Issue by MiguelLatorre** [itchyny/lightline.vim#162]
Thanks so much for this plugin.
I'm trying to port my config from airline.
I'm reading autoload/lighline.vim and I see:
```
\   'component_visible_condition': {
\     'modified': '&modified||!&modifiable', 'readonly': '&readonly', 'paste': '&paste'
\   },
```

Shouldn't be "spell" in that array?
Currently I have to have in my .vimrc:
```
\ 'component_visible_condition': {
\   'spell': '&spell',
\ },
```

Also ..., I cannot figure out how to set colors for a component, just say "readonly" in red.

**Comment by itchyny** [comment]
The spell component is visible (shows `'no spell'`) when `'spell'` is off so I think that the current implementation is correct. It's like the `filetype` component, which shows `'no ft'` when `&ft` is empty, and the visible condition is not set.

In order to change the colours of a component, you can use `component_expand`. The idea and its behaviour is a little bit difficult, but here's a working example of colouring the readonly component red.
```vim

let g:lightline = {
      \ 'component_expand': {
      \   'readonly': 'LightLineReadOnly',
      \ },
      \ 'component_type': {
      \   'readonly': 'error',
      \ },
      \ }
function! LightLineReadOnly()
  return &readonly ? 'RO' : ''
endfunction
```

**Comment by MiguelLatorre** [comment]
Ok, I see it's visible, always visible, what I meant is something like the _modified_, _readonly_ and _paste_ flags, all of them are on/off values and they change their visibility according to their state.

I think the _&spell_ flag is exactly like the others in the current component_visible_condition. 

One can set a different filetype, but it cannot be on/off "toggled" (I guess).

BTW, thanks for the colouring example.

Anyway, I guess it's a matter of different point of view, I'll close the issue.

Thanks so much, I really appreciate it.

**Comment by itchyny** [comment]
OK, I thought your opinion is reasonable, I changed the default setting of the spell component. Thanks for your feedback.
