### ISSUE TITLE
Line does not show with lazyredraw and scrollable buffer

### ISSUE THREAD

**Issue by silverwind** [itchyny/lightline.vim#165]
When `lazyredraw` is set and a scrollable file is opened, I get an empty initial rendering of the statusline:

![](https://cloud.githubusercontent.com/assets/115237/15801145/0f7196d6-2a8c-11e6-860e-99fa5771e811.png)

If I then move the cursor, the statusline gets drawn properly:

![scroll](https://cloud.githubusercontent.com/assets/115237/15801118/85b2e382-2a8b-11e6-8140-8e20c58d699c.png)

Obviously, I'd like to keep `lazyredraw` enabled. See my [`.vimrc`](https://github.com/silverwind/dotfiles/blob/master/.vimrc) for my full configuration.

**Comment by itchyny** [comment]
I tested your configuration but cannot reproduce. I tested on two environment, iTerm2 + Vim 7.4 + TERM=xterm-256color on Mac OS X and terminator + Vim 7.4 on Ubuntu. I doubt it some bug caused by the combination of your terminal, Vim version and $TERM. It might be a dirty workaround but `autocmd VimEnter * redraw` may fix it.

**Comment by silverwind** [comment]
Looks to be platform/terminal specific. I only have the issue using Mintty on Cygwin. Iterm2 on OS X is fine with the same configuration. Will try your workaround.

**Comment by silverwind** [comment]
Confirming the workaround works, I can live with it, thanks!
