### ISSUE TITLE
Change background color of status bar only (to make it match the background of the terminal)

### ISSUE THREAD

**Issue by MindTooth** [itchyny/lightline.vim#168]
Hi,
I use base16, and would want the statusbar to have same color, or to appear transparent.  Now it has a dark tint to it.  Tried to find anything related in the docs, or issue.  But came up empty.

![screen shot 2016-07-11 at 16 17 55](https://cloud.githubusercontent.com/assets/35828/16733831/70587d48-4783-11e6-8963-6a9d9ab23fba.png)

Using Tmuxline, and managed to remove the background.  And would love to do the same with Vim :-)

Thank you for the plugin though :-)

**Comment by itchyny** [comment]
How about this configuration?
```vim
let s:palette = g:lightline#colorscheme#{g:lightline.colorscheme}#palette
let s:palette.normal.middle = [ [ 'NONE', 'NONE', 'NONE', 'NONE' ] ]
let s:palette.inactive.middle = s:palette.normal.middle
let s:palette.tabline.middle = s:palette.normal.middle
```

**Comment by MindTooth** [comment]
![Bossman](https://cl.ly/ggh7/download/Image%202016-07-13%20at%208.41.04%20AM.png)

You're the boss man! :-D  Much appreciated!

**Comment by sp0ng3w0rthy** [comment]
I never though I'd find an answer for this, thanks man.

**Comment by jonmackenzie** [comment]
I'm getting `Undefined variable: g:lightline#colorscheme#wombat#palette`

has anything changed or am I just missing something?

**Comment by syphar** [comment]
@jonmackenzie just tried to solve the same issue, 

for me the combination of this code, and the one from https://github.com/itchyny/lightline.vim/issues/381#issuecomment-523529581 worked. 

```viml
autocmd VimEnter * call SetupLightlineColors()
function SetupLightlineColors() abort
  " transparent background in statusbar
  let l:palette = lightline#palette()

  let l:palette.normal.middle = [ [ 'NONE', 'NONE', 'NONE', 'NONE' ] ]
  let l:palette.inactive.middle = l:palette.normal.middle
  let l:palette.tabline.middle = l:palette.normal.middle

  call lightline#colorscheme()
endfunction
```

**Comment by shaunsingh** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/71196912/113178818-f27dc380-921c-11eb-9a79-bda32a3d9672.png">
 
even after putting the above block in my .vimrc, parts of the status line remain colored (specifically the grey parts) 
<img width="399" alt="image" src="https://user-images.githubusercontent.com/71196912/113178917-0de8ce80-921d-11eb-9870-5e58f9b6fe9d.png">

Is there any way to make these parts transparent? I tried to set the grey color to same color as my background, but it produces this weird looking light blue instead, I assume it uses 16-colors instead of 256
