### ISSUE TITLE
Installation without a plugin manager

### ISSUE THREAD

**Issue by salamander2** [itchyny/lightline.vim#260]
Please add documentation on how to install this when the user does not have a vim plugin manager (eg vundle). Assume a clean install of vim (sudo apt-get install vim vim-doc) Which directories need to be created, which files need to be put where?

Thanks.

**Comment by itchyny** [comment]
Please refer to `:h lightline-problem-1`, it says `Put all the files under $VIM.`.

**Comment by salamander2** [comment]
I don't see that anywhere in your Readme.MD (so I don't know what :h is), but thanks, I'll do that.

**Comment by itchyny** [comment]
Ah, yes, I apologize. I should have mentioned it is a command in Vim but you may not reach the reference because you have not installed yet. I think I didn't (and will not) write in README.md because I strongly recommend Vim plugins using plugin managers. Managing the plugin directories or `runtimepath` by hand is full of pain.

**Comment by salamander2** [comment]
Yes. I have just discovered that. So I'll find a simple plugin-manager. I am trying to get the tender.vim lightline bar to work which looks really cool. see https://github.com/jacoborus/tender.vim 
 But why am I wasting time when I should be working?! :)

**Comment by itchyny** [comment]
Sorry for that. There're some choices for plugin manager but I think https://github.com/junegunn/vim-plug is popular these days.
