### ISSUE TITLE
Changing colour of status bar to same as background gives extra right separator 

### ISSUE THREAD

**Issue by jjo93sa** [itchyny/lightline.vim#294]
I'm trying out iTerm2 and solarized colour scheme. With this combination, I get a status line with a different colour than the vim background:

<img width="650" alt="screen shot 2018-03-16 at 14 37 34" src="https://user-images.githubusercontent.com/15944915/37526687-f544581a-2927-11e8-9a0e-31177662a76c.png">

I found another issue that resolved it (using the 4 commented-out lines in the screen shot): https://github.com/itchyny/lightline.vim/issues/168

However, when I use these lines, which does make the background the same colour as vim, lightline seems to display an extra right separator, just to the word "unix" in the image below:

<img width="762" alt="screen shot 2018-03-16 at 14 36 09" src="https://user-images.githubusercontent.com/15944915/37526766-283fdaa0-2928-11e8-83a3-d09be2e5fdee.png">

I've tried, but I can't seem to get rid of this separator. And I can't find an explanation for why it appears with one background colour but not another? Please help - I can waste a whole day on this sort of thing!

**Comment by itchyny** [comment]
This seems to be a difficult problem. I think it's simple to solve by assigning the exact same colors as the background of the colorscheme. What does `:hi Normmal` show?

**Comment by jjo93sa** [comment]
With and without those four "palette" lines: 
Normal         xxx ctermfg=12

**Comment by itchyny** [comment]
The only _solution_ I could found was inserting extra color in normal.right pallete.
```vim
let s:palette = g:lightline#colorscheme#{g:lightline.colorscheme}#palette
let s:palette.normal.middle = [ [ 'NONE', 'NONE', 'NONE', 'NONE' ] ]
let s:palette.inactive.middle = s:palette.normal.middle
let s:palette.tabline.middle = s:palette.normal.middle
call insert(s:palette.normal.right, s:palette.normal.left[1], 0)
```
Honestly this could be a kind of bug of the plugin, but skipping the separator based on the palette could cause many other problems, so let me close this with wontfix. Also I don't recommend using patched font these days because it leads to less portability (I removed the instruction from README.md months ago).

**Comment by jjo93sa** [comment]
Thanks - for the record (in case anyone stumbles on this thread) when I use this:

`let s:palette = g:lightline#colorscheme#{g:lightline.colorscheme}#palette
let s:palette.normal.middle = [ [ 'NONE', 'NONE', 'NONE', 'NONE' ] ]
let s:palette.inactive.middle = s:palette.normal.middle
let s:palette.tabline.middle = s:palette.normal.middle
call insert(s:palette.normal.right, s:palette.normal.left[1], 0)`

I get a status line looking like this:

<img width="663" alt="screen shot 2018-03-17 at 09 41 26" src="https://user-images.githubusercontent.com/15944915/37553845-692ef808-29c7-11e8-82f0-fdcea3388920.png">

Which I actually quite like.

Regarding your comment about patched font, please could you explain? Does this relate to the lines:

`
      \ 'separator': { 'left': '', 'right': '' },
`
 `     \ 'subseparator': { 'left': '', 'right': '' }
`

**Comment by itchyny** [comment]
Right, that triangles are special characters assigned in the patched fonts. I thought the powerline-lish style triangles are cool when I started developing this plugin, but I don't recommend using the triangles these days because the statusline will messed up when the font is not installed, the configuration is not portable in some sense. Of course, it can be used from now on and will never be dropped off the support forever. Much effort has been spent for coloring the separators in the code but still causes far difficult problem like this. The default empty separators do not cause the problem, you know.
