### ISSUE TITLE
Feature Request(s) - Inactive Colorscheme & Separator

### ISSUE THREAD

**Issue by weilbith** [itchyny/lightline.vim#336]
I would like to ask if it would be possible to don't only have different segment lists for active or inactive windows, but also different colorschemes. So I think it could look pretty handsome if an inactive windows statusline have different colors (e.g. more calm). This would support the eyes focus to the active window or at least determine which one is the active one. For example _Airline_ provides the `palette.inactive` definition.
Moreover, what _Airline_ is not able to do completely and has been handled in these issues ([#1236](https://github.com/vim-airline/vim-airline/issues/1236), [#1249](https://github.com/vim-airline/vim-airline/pull/1249)) are inactive separators using the foreground color. The idea is that a passive statusline could set all back- and foreground colors to the same. Looks especially nice when using the same as the window borders (setting `VertSplit` back- and foreground to same color leads to a nice homogeneous bar). But in such case all separators would disappear. Therefore a new separator which takes the foreground also, would look pretty cool. _Airline_ has some so called _alternative separators_, but they don't take the foreground color.

I tried to illustrate this in the following images.
An partial active colorful (?) statusline:
![37335721-9078eb0a-26af-11e8-9ad5-ef7af6ca16ce](https://user-images.githubusercontent.com/12543647/49704472-d4d35d00-fc13-11e8-917e-5e6df64c0678.jpg)

Inactive statusline with a different colorscheme (segments stay here the same):
![37335727-9386f90e-26af-11e8-98f4-3f56c2a97f76](https://user-images.githubusercontent.com/12543647/49704480-f2082b80-fc13-11e8-88f5-beadd6b25201.jpg)

Also inactive statusline, but using the special separators:
![37335734-957006fc-26af-11e8-9c96-a7a61308cd17](https://user-images.githubusercontent.com/12543647/49704488-fe8c8400-fc13-11e8-82d6-5144ad88e0cd.jpg)

What are your thoughts about this? I guess the second part with the separators could become hard (since it is not only a new separator but also special color for a corner case), but at least to inactive color scheme shouldn't be that problem, right?

**Comment by itchyny** [comment]
The statusline of inactive windows have different colors in lightline, as one lightline colorscheme has both color sets for active and inactive windows. See https://github.com/itchyny/lightline.vim/blob/688240e0ef849cdc8457822658cedf10358c75d6/autoload/lightline/colorscheme/landscape.vim#L11-L12 for example, the inactive key of the palette specifies the colors of inactive statusline. Am I answering to your question right?

**Comment by weilbith** [comment]
Oh, I'm sorry. Have read through the whole documentation and searched for it, but wasn't able to find it. But that's awesome, thanks!

What about the other part? :upside_down:

**Comment by itchyny** [comment]
I've checked some colorschemes of lightline but I can see the separators because the background colors are slightly different for even inactive windows.

<img width="309" alt="screen shot 2018-12-13 at 11 07 01" src="https://user-images.githubusercontent.com/375258/49910771-5bfc2b80-fec7-11e8-88f7-6a9103c7f17a.png">
<img width="287" alt="screen shot 2018-12-13 at 11 08 18" src="https://user-images.githubusercontent.com/375258/49910894-c745fd80-fec7-11e8-8373-2789607d8a3c.png">
<img width="287" alt="screen shot 2018-12-13 at 11 08 34" src="https://user-images.githubusercontent.com/375258/49910898-cad98480-fec7-11e8-90d5-beccf3dc7329.png">
<img width="284" alt="screen shot 2018-12-13 at 11 09 00" src="https://user-images.githubusercontent.com/375258/49910899-cdd47500-fec7-11e8-860d-8ef7b5e601dc.png">
<img width="299" alt="screen shot 2018-12-13 at 11 09 18" src="https://user-images.githubusercontent.com/375258/49910906-d167fc00-fec7-11e8-9130-8140155eacfd.png">

There must be some exceptions, but I don't think it's worth implementing special separators for inactive windows. Users can concatenate the components (I mean changing `[ [ x, y ], [ z ] ]` to `[ [ x, y, z ] ]`) to see the subcomponents to be appeared. Sorry for inconvenience but it's an expected behavior.

**Comment by itchyny** [comment]
I've checked some colorschemes of lightline but I can see the separators because the background colors are slightly different for even inactive windows.

<img width="309" alt="screen shot 2018-12-13 at 11 07 01" src="https://user-images.githubusercontent.com/375258/49910771-5bfc2b80-fec7-11e8-88f7-6a9103c7f17a.png">
<img width="287" alt="screen shot 2018-12-13 at 11 08 18" src="https://user-images.githubusercontent.com/375258/49910894-c745fd80-fec7-11e8-8373-2789607d8a3c.png">
<img width="299" alt="screen shot 2018-12-13 at 11 09 18" src="https://user-images.githubusercontent.com/375258/49911128-8c909500-fec8-11e8-8071-6604b41d4a4c.png">

There must be some exceptions, but I don't think it's worth implementing special separators for inactive windows. Users can concatenate the components (I mean changing `[ [ x, y ], [ z ] ]` to `[ [ x, y, z ] ]`) to see the sub-separators to be appeared. Sorry for inconvenience but it's an expected behavior.

**Comment by weilbith** [comment]
No, actually the last sentence is is the solution I think. :thinking:
After all that should it be. Thanks for the answer!
At least I can define also an inactive colorscheme where all colors are pretty the same and juts add some brightness factor.
Thank you so much for helping me with my questions. Looking forward to have a night switching from _Airline_ and make all work and looking nice. :v:
