### ISSUE TITLE
glyph not displayed for coc.nvim integration

### ISSUE THREAD

**Issue by Char-Aznable** [itchyny/lightline.vim#343]
I have followed coc.nvim's doc for putting coc-status in lightline status bar:
```
  let g:lightline = {
	\ 'colorscheme': 'wombat',
	\ 'active': {
	\   'left': [ [ 'mode', 'paste' ],
	\             [ 'cocstatus', 'readonly', 'filename', 'modified' ] ]
	\ },
	\ 'component_function': {
	\   'cocstatus': 'coc#status'
	\ },
\ }
```
The problem is that the error glyph does not show up correctly (it's shown as a box of string) even though I have set the error glyph as a capital `x` (`X`) in coc.nvim:
```
"coc.preferences.diagnostic.errorSign": "X",
"coc.preferences.diagnostic.warningSign": "⚠",
"coc.preferences.diagnostic.infoSign": ">>",
"coc.preferences.diagnostic.hintSign": ">>",
```
The strange thing is that the warning glyph shows up in the status bar correctly. Also, all glyphs show up correctly in the sign column in vim but they just got messed up somehow in the status bar.

**Comment by itchyny** [comment]
This seems to be an issue of coc.nvim so please report to the repository of coc.nvim. If you still think this is an issue of lightline, please paste the minimal vimrc, screenshots and the precise steps to reproduce the problem (so that anyone who does not know what coc.nvim is for can understand what the problem is and what the reporter expect).

**Comment by Char-Aznable** [comment]
Never mind. I found the problem

**Comment by physicistgeng** [comment]
i have the exactly same issue, how do you fix this?
