### ISSUE TITLE
Dynamic update from function not working

### ISSUE THREAD

**Issue by yngwi** [itchyny/lightline.vim#374]
Hi,

I'm currently using the "Ayu" theme that provides it's own lightline theme. I want to create a function that allows me to toggle the light/dark variants of the theme as I like to use them during day/night. I created the following function:

```viml
function! ToggleSchemeColor()
    if g:ayucolor == "light"
        let g:ayucolor="dark"
    else
        let g:ayucolor="light"
    endif
    colorscheme ayu
    call lightline#init()
    call lightline#colorscheme()
    call lightline#update()
endfunction

nnoremap <silent><C-k> :call ToggleSchemeColor()<CR>
```

It works as expected regarding the ayu color scheme but the lightline scheme doesn't change. It stays in the way it was initially set up in the vim config (light scheme). Due to the fact that I'm new to vim it's possible that I try to do something impossible or made some other mistake. Could you please help me correcting my function? Thank you!

Daniel

**Comment by itchyny** [comment]
That's because once [the autoload file](https://github.com/ayu-theme/ayu-vim/blob/master/autoload/lightline/colorscheme/ayu.vim) is sourced, it will never been reloaded automatically. Instead, you can use `execute 'source' globpath(&rtp, 'autoload/lightline/colorscheme/ayu.vim')` just before `lightline#colorscheme`, to forcibly reflect the update of the colorscheme.

**Comment by yngwi** [comment]
Great, thank you so much, it works!
