### ISSUE TITLE
The order of the tabs is unintuitive when placed on the right side of the tabline

### ISSUE THREAD

**Issue by grenmester** [itchyny/lightline.vim#440]
When there are several tabs open in one session, the ordering of the tabs don't seem to make sense. This works the way you would expect it to when the tabs are on the left side of the tabline with the tab numbers increasing from left to right. When it's on the right side of the tabline it looks off. This is how the ordering looks like:

![image](https://user-images.githubusercontent.com/13500910/78566653-244e8b00-7852-11ea-86d9-336fd6a0533c.png)

It gets even more confusing when you switch tabs as the order of the tabs changes. Is this happening because the tabs component is supposed to be used only on the left side or is there some other reason?

A similar thing happens when I display my buffers on the right side of the tabline using https://github.com/mengelbrecht/lightline-bufferline so it seems like it has to do with some kind of buffer/tab ordering logic.

**Comment by itchyny** [comment]
Thanks for your report and the short answer is, please reverse the result when you display expansion components on the right for now.
```vim
let g:lightline.component_expand = {'buffers': 'LightlineBufferlineRight'}

function! LightlineBufferlineRight()
  return reverse(lightline#bufferline#buffers())
endfunction
```

I know this behavior since I created the plugin and now I think this is a design decision failure. The order is always from outside to inside (not from left to right) and this rule applies to expansion components, components list declarations and the colorscheme palette. Therefore fixing this behavior breaks all the existing lightline colorschemes and the order of components on the right hand side for people who has their own configuration. Fixing only the behavior of expansion components introduces weird code to the plugin. The colorscheme arrays applies from outside to inside and I thought this is consistent behavior 7 years ago, but I have to admit the rule introduces this confusing order of expansion components.

**Comment by grenmester** [comment]
Thanks! This works for buffers. For those who want it to work for tabs, this is how you do it:

```vim
function! LightlineTabRight()
  return reverse(lightline#tabs())
endfunction

let g:lightline.component_expand = {'rtabs': 'LightlineTabRight'}
let g:lightline.component_type = {'rtabs': 'tabsel'}
```
