### ISSUE TITLE
component_expand issue

### ISSUE THREAD

**Issue by noscript** [itchyny/lightline.vim#507]
I'm having trouble getting this to work:

```vim
let g:lightline = {
	  \ 'active': {
	  \   'right': [ [ 'my_flag' ] ]
	  \ },
	  \ 'component_expand': {
	  \   'my_flag': 'MyFlag', " doesn't work
	  " \   'my_flag': 'MyFlagPre', " works
	  \ },
	  \ 'component_type': {
	  \   'my_flag': 'error',
	  \ }
	  \ }

function! MyFlagPre() abort
  return '%{MyFlag()}'
endfunction

function! MyFlag() abort
  return &modified ? '+' : ''
endfunction
```

The idea is to evaluate the component in the context of current window.

Basically I would like to [understand](https://github.com/itchyny/lightline.vim/issues/161) why I have to create wrapper functions that do `%{...}` and if there is a cleaner way, something like

```vim
let g:lightline.component_expand_raw': {
	  \   'my_flag': '%{MyFlag()}', 
	  \ }
```

**Comment by itchyny** [comment]
You `call lightline#update()` correctly, right? Calling this function is required to update the contents of `component_expand`.

**Comment by noscript** [comment]
Actually I don't call it anywhere. What's the best way to do it in my case? Set a timer, or use autocommand?

**Comment by itchyny** [comment]
You can call `lightline#update` on the `TextChanged` event, but since it is triggered too frequent so it sacrifice the performance. I don't think the modified flag is an error so I propose to start with `component_function`. Users are recommended to use `component_expand` for components indicating some errors or warnings. Most of syntax-checking plugins have hooks triggered after their checks where users can update the lightline statusline.

**Comment by noscript** [comment]
Thank you, that made things a lot clearer to me.
