### ISSUE TITLE
highlighting is lost when colorscheme is applied twice (nightly vim)

### ISSUE THREAD

**Issue by habamax** [itchyny/lightline.vim#512]
vim version: 8.2.1728 

Steps to reproduce:

1. open vim
2. `:colo default`
3. `:colo default`

![vim-lightline](https://user-images.githubusercontent.com/234774/94190637-0be03480-feb5-11ea-8ef8-7a485db0310b.gif)

One can "fix" it by going into visual or insert mode.

Another one is to use autocommand: 

```
augroup lightline_hl | au!
    au Colorscheme * call lightline#disable() | call lightline#enable()
augroup END
```

source: https://vi.stackexchange.com/questions/27448/suddenly-running-colorscheme-breaks-lightline

**Comment by habamax** [comment]
calling `:call lightline#highlight()` has no effect, but if I manually do `hi LightlineLeft_active_0 guibg=red` it works:

![image](https://user-images.githubusercontent.com/234774/94191608-6a59e280-feb6-11ea-8333-a0483e00f27d.png)

**Comment by yhu266** [comment]
Related patch (8.2.1703): https://github.com/vim/vim/commit/213da551dec465e193619684b260bf9d5a8d6afc.

Although, I suspect this is a vim issue, since their developers changed highlight behaviors. And as Bram commented in https://github.com/vim/vim/pull/6970#issuecomment-694394855, it may be fixed in the future vim release.
> Thanks. This changes behavior a bit, but it won't cause problems, right? If someone finds that it breaks their existing setup, we probably only find out by including the patch.

**Comment by itchyny** [comment]
This issue has been fixed. Thanks for reporting.
