### ISSUE TITLE
On colorschemes

### ISSUE THREAD

**Issue by scrouthtv** [itchyny/lightline.vim#573]
Hello,

I think there are some minor issues with the `colorscheme.md` file:
 - Some colorschemes are named with two words even though they should be seperated by an _ (e.g. `PaperColor dark` should be `PaperColor_dark` instead, etc.
 - `PaperColor` is exists but is not mentioned at all
 - `solarized_dark` and `solarized_light` are mentioned but don't actually exist, however, there is a colorscheme named `solarized` which is not mentioned in the doc
 - same with `one` and `16color`

I just found these when I tried the different colorschemes today, let me know if I'm missing anything.

**Comment by scrouthtv** [comment]
Also, how exactly do I specify my own colorscheme? According to the help
```
In general, each palette follows the following style:
>
	let s:p.{mode}.{where} = [ [ {guifg}, {guibg}, {ctermfg}, {ctermbg} ], ... ]
<
```

However, every colorscheme I've looked at so far uses some other format (e.g. `PaperColor`):
```
let s:p.replace.left = [ [ s:background, s:pink ], [s:statusline_active_fg, s:status ], [ s:statusline_active_fg, s:statusline_active_bg ] ]
```
Why are there multiple arrays inside the array? Why do they each have only two elements instead of the four according to the help?

**Comment by itchyny** [comment]
The list of `colorscheme.md` shows all the background variants so it is fine. The titles are not corresponding to the colorscheme name so it might confusing for you.
The help on the colorscheme palette is collect. Some colorscheme definitions use `lightline#colorscheme#fill` to derive cterm colors from gui colors, or `lightline#colorscheme#flatten` to flatten gui/cterm color tuples.
In order to make the text bold, specify `'bold'` to the 5th element.
