### ISSUE TITLE
How do I use custom colors?

### ISSUE THREAD

**Issue by joetemp** [itchyny/lightline.vim#98]
Trying to figure out how to customize colors. How does one go about this? Any help is greatly appreciated.

**Comment by joetemp** [comment]
And I don't mean via a pre-made color scheme. Like how would one manually change a color or two?

**Comment by khtdr** [comment]
See autoload/lightline/colorscheme/* You can experiment with colors in there.

**Comment by itchyny** [comment]
Right. Please create your colorscheme. The help (:h lightline) describes how to do it.

**Comment by sheerun** [comment]
@itchyny I tried to create my own scheme that bases on `powerline`, but I'm unable to do so because its uses a function that is not available before `lightline.vim` is loaded:

```
let g:lightline#colorscheme#powerlineish#palette = lightline#colorscheme#fill(s:p)
```

any ideas how to overcome this? Could lightline call `lightline#colorscheme#fill` by itself instead requiring plugins to do so?

**Comment by itchyny** [comment]
@sheerun Please refer to `:h lightline-colorscheme` for details of creating a lightline colorscheme. You can call the fill function after lightline plugin path is added to &runtimepath. You can avoid the fill function by defining all the guifg, guibg, ctermfg, ctermbg colors and this is the default configuration of lightline colorscheme. The fill function is just a shortcut for filling cterm colors, introduces some overhead and should not be the default.
